[tool.poetry]
name = "online-cinema-backend"
version = "0.1.0"
description = "Backend for Online Cinema with FastAPI"
authors = ["Vitalii Ivanchenko <vanno1234567890@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
fastapi = {extras = ["standard"], version = "^0.115.0"}
sqlalchemy = "^2.0.48"
alembic = "^1.18.4"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
bcrypt = "4.0.1"
python-jose = {extras = ["cryptography"], version = "^3.5.0"}
celery = "^5.6.3"
redis = "^7.4.0"
stripe = "^15.1.0"
pydantic-settings = "^2.14.0"
psycopg2-binary = "^2.9.9"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
flake8 = "^7.0.0"
black = "^24.0.0"
mypy = "^1.8.0"
types-python-jose = "^3.5.0.20260408"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[[tool.mypy.overrides]]
module = [
    "celery.*",
    "jose.*"
]
ignore_missing_imports = true
