"""add_unique_to_genre_name

Revision ID: efbb41bb0f2d
Revises: c45ecb3dad39
Create Date: 2026-04-07 02:19:36.118964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efbb41bb0f2d'
down_revision: Union[str, Sequence[str], None] = 'c45ecb3dad39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_genre_name', ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_constraint('uq_genre_name', type_='unique')

    # ### end Alembic commands ###
